---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-server
  namespace: benchmark
data:
  config.yaml: |
    ---
    debug: false
    appPort: 50051
    metricsPort: 8081
    database:
      host: your_db_host
      database: your_db_name
      maxConnections: 10
      sslmode: require
      channel_binding: require