---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: benchmark
spec:
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: 50051
    targetPort: http
  selector:
    app: grpc-server
  type: ClusterIP